---
- name: Run Tests on remote machine
  hosts: all
  gather_facts: no
  vars:
      training_home: ../
      linux_user: ubuntu

  tasks:

    - name: Start a container with sleep 3 for testing
      community.docker.docker_container:
        name: sleepy
        image: alpine
        debug: true
        command: ["sleep", "3"]
